/**
 * Clinical Reference Ranges, Psychometric Norms, and Research Notes
 * Every entry contains a `source` field. Numbers without confirmed published literature
 * are explicitly labeled "needs clinical review".
 */

export const MEASURE_REFERENCES = {
  pvt_mean_rt: {
    id: 'pvt_mean_rt',
    name: 'PVT Mean Reaction Time',
    unit: 'ms',
    typicalRange: '220 – 290 ms',
    source: 'Basner & Dinges (2011), Sleep; Roizen et al. (2019)',
    plainMeaning: 'Average visual response speed to sudden unexpected target stimuli.',
    clinicalNote: 'Slowed mean RT indicates reduced psychomotor vigilance, sedating fatigue, or attentional lapses.',
    isTypical: (v) => v >= 190 && v <= 320,
    isBorderline: (v) => (v > 320 && v <= 370) || (v < 190 && v >= 160),
  },
  pvt_rt_sd: {
    id: 'pvt_rt_sd',
    name: 'PVT Reaction Time Variability (SD)',
    unit: 'ms',
    typicalRange: '18 – 45 ms',
    source: 'Kofler et al. (2013), Psychological Bulletin; Tamm et al. (2012)',
    plainMeaning: 'How consistently your response speed remained steady from trial to trial.',
    clinicalNote: 'Intra-individual reaction time variability (IIV) is a core neurobiological marker of ADHD alerting instability.',
    isTypical: (v) => v <= 48,
    isBorderline: (v) => v > 48 && v <= 65,
  },
  pvt_rt_cv: {
    id: 'pvt_rt_cv',
    name: 'RT Coefficient of Variation (CV)',
    unit: 'ratio',
    typicalRange: '< 0.15 (15%)',
    source: 'Klein et al. (2006); Kofler et al. (2013)',
    plainMeaning: 'Reaction variability adjusted for overall baseline speed (SD / Mean).',
    clinicalNote: 'Standardizes trial-to-trial instability across individuals with different baseline reaction speeds.',
    isTypical: (v) => v <= 0.16,
    isBorderline: (v) => v > 0.16 && v <= 0.22,
  },
  pvt_lapses: {
    id: 'pvt_lapses',
    name: 'Attentional Lapses (>500ms)',
    unit: 'count',
    typicalRange: '0 – 1 lapses',
    source: 'Dinges & Powell (1985); Basner et al. (2015)',
    plainMeaning: 'Moments where response took more than half a second.',
    clinicalNote: 'Represents micro-dropouts in sustained attentional readiness.',
    isTypical: (v) => v <= 1,
    isBorderline: (v) => v === 2,
  },
  pvt_fast_responses: {
    id: 'pvt_fast_responses',
    name: 'Premature & Impulsive Presses (<150ms)',
    unit: 'count',
    typicalRange: '0 – 1 count',
    source: 'Basner & Dinges (2011)',
    plainMeaning: 'Responses triggered prematurely before stimulus or without sensory verification.',
    clinicalNote: 'Indicates motor impulsivity, false anticipation, or failure of motor restraint.',
    isTypical: (v) => v <= 1,
    isBorderline: (v) => v === 2,
  },
  stroop_cost: {
    id: 'stroop_cost',
    name: 'Stroop Interference Cost',
    unit: 'ms',
    typicalRange: '+70 to +150 ms',
    source: 'MacLeod (1991), Psychological Bulletin; Stroop (1935)',
    plainMeaning: 'Extra brain processing time required when word text conflicts with ink color.',
    clinicalNote: 'Reflects anterior cingulate cortex and dorsolateral prefrontal inhibitory resolution.',
    isTypical: (v) => v <= 155,
    isBorderline: (v) => v > 155 && v <= 195,
  },
  stroop_accuracy: {
    id: 'stroop_accuracy',
    name: 'Stroop Inhibition Accuracy',
    unit: '%',
    typicalRange: '≥ 90%',
    source: 'Miyake et al. (2000), Cognitive Psychology',
    plainMeaning: 'Percentage of conflict color trials answered correctly.',
    clinicalNote: 'Measures executive suppression of automated reading habits under sensory conflict.',
    isTypical: (v) => v >= 88,
    isBorderline: (v) => v >= 75 && v < 88,
  },
  digit_span: {
    id: 'digit_span',
    name: 'Working Memory Digit Span',
    unit: 'digits',
    typicalRange: '5 – 9 digits',
    source: "Miller (1956); Cowan (2001), Behavioral and Brain Sciences",
    plainMeaning: 'Length of number sequences held accurately in immediate memory.',
    clinicalNote: 'Evaluates the capacity of the phonological loop and active executive working memory buffer.',
    isTypical: (v) => v >= 5,
    isBorderline: (v) => v === 4,
  },
  verbal_speech_rate: {
    id: 'verbal_speech_rate',
    name: 'Verbal Fluency Speech Rate',
    unit: 'WPM',
    typicalRange: '120 – 160 WPM',
    source: 'Yuan et al. (2006); Goldman-Eisler (1968)',
    plainMeaning: 'Words spoken per minute during free-form category naming.',
    clinicalNote: 'Evaluates lexical retrieval kinetics, phonation consistency, and executive initiation.',
    isTypical: (v) => v >= 110 && v <= 175,
    isBorderline: (v) => (v >= 95 && v < 110) || (v > 175 && v <= 195),
  },
  verbal_pause_ratio: {
    id: 'verbal_pause_ratio',
    name: 'Speech Hesitation / Pause Ratio',
    unit: '%',
    typicalRange: '10% – 22%',
    source: 'Campione & Véronis (2002); needs clinical review for remote browser audio',
    plainMeaning: 'Percentage of time spent in silence/hesitation while generating answers.',
    clinicalNote: 'Reflects word-finding latency, executive formulation effort, or vocal hesitancy.',
    isTypical: (v) => v <= 22,
    isBorderline: (v) => v > 22 && v <= 30,
  },
  gaze_on_screen: {
    id: 'gaze_on_screen',
    name: 'On-Screen Gaze Fixation Ratio',
    unit: '%',
    typicalRange: '≥ 90%',
    source: 'Holmqvist et al. (2011), Eye Tracking Guide; needs clinical review for webcam tracking',
    plainMeaning: 'Percentage of testing time eyes remained oriented toward the stimulus display.',
    clinicalNote: 'Webcam-based proxy for visual distraction and off-task glances.',
    isTypical: (v) => v >= 88,
    isBorderline: (v) => v >= 78 && v < 88,
  },
  fixation_dispersion: {
    id: 'fixation_dispersion',
    name: 'Gaze Fixation Dispersion',
    unit: 'px',
    typicalRange: '25 – 55 px (~0.6°–1.4° visual angle at 60cm)',
    source: 'Rayner (1998); Hessels et al. (2018); needs clinical review for device pixel mapping',
    plainMeaning: 'Spread and micro-wandering of gaze coordinates during steady target viewing.',
    clinicalNote: 'Pixel values depend on webcam focal length, screen resolution, and distance. Qualitative indicator.',
    isTypical: (v) => v <= 56,
    isBorderline: (v) => v > 56 && v <= 70,
  },
  blink_rate: {
    id: 'blink_rate',
    name: 'Spontaneous Blink Rate',
    unit: 'blinks/min',
    typicalRange: '14 – 22 / min',
    source: 'Stern et al. (1994), Psychophysiology; Doughty (2001)',
    plainMeaning: 'Spontaneous eye blinks per minute.',
    clinicalNote: 'Elevated rates reflect cognitive fatigue, eye strain, or dopamine-mediated arousal changes.',
    isTypical: (v) => v >= 12 && v <= 24,
    isBorderline: (v) => (v >= 8 && v < 12) || (v > 24 && v <= 30),
  },
  head_jitter: {
    id: 'head_jitter',
    name: 'Head Pose Steadiness',
    unit: 'deg² var',
    typicalRange: '< 4.5° variance',
    source: 'Martin et al. (2018); needs clinical review for webcam tracking',
    plainMeaning: 'Physical head posture steadiness and micro-movement in front of the camera.',
    clinicalNote: 'Objective marker of gross motor restlessness, fidgeting, and postural adjustments.',
    isTypical: (v) => v <= 4.8,
    isBorderline: (v) => v > 4.8 && v <= 7.0,
  },
};

export const SCREENER_REFERENCES = {
  asrs: {
    id: 'asrs',
    name: 'Adult ADHD Self-Report Scale (ASRS v1.1)',
    cutoff: 'Part A ≥ 4 shaded boxes',
    population: 'Adults (18+)',
    source: 'Kessler et al. (2005), World Health Organization; Adler et al. (2006)',
    clinicalNote: 'Standard brief adult ADHD screener. High sensitivity (~68-80%) and specificity (~95%) for identifying traits warranting full psychiatric assessment.',
  },
  aq10: {
    id: 'aq10',
    name: 'Autism Spectrum Quotient (AQ-10 Adult)',
    cutoff: 'Score ≥ 6 / 10',
    population: 'Adults (18+)',
    source: 'Allison, Auyeung, & Baron-Cohen (2012), BMJ; NICE Clinical Guideline CG142',
    clinicalNote: 'Endorsed by the UK National Institute for Health and Care Excellence (NICE) as an initial triage screener for referral.',
  },
  catq: {
    id: 'catq',
    name: 'Camouflaging Autistic Traits Questionnaire (CAT-Q)',
    cutoff: 'Total score ≥ 100',
    population: 'Adults & Adolescents (16+)',
    source: 'Hull et al. (2019), Journal of Autism and Developmental Disorders',
    clinicalNote: 'Measures social compensation, masking, and assimilation strategies used to navigate neurotypical social environments.',
  },
  vanderbilt: {
    id: 'vanderbilt',
    name: 'Vanderbilt ADHD Parent Rating Scale',
    cutoff: '≥ 6 symptoms rated "often" (2) or "very often" (3) in Inattentive or Hyperactive domains',
    population: 'Children (Ages 4–15)',
    source: 'Wolraich et al. (2003), Journal of Pediatric Psychology; AAP Clinical Practice Guidelines',
    clinicalNote: 'Validated DSM-based pediatric rating instrument used by pediatricians and child psychiatrists.',
  },
  aq_child: {
    id: 'aq_child',
    name: 'Autism Spectrum Quotient (AQ-10 Child)',
    cutoff: 'Score ≥ 6 / 10',
    population: 'Children (Ages 4–11)',
    source: 'Allison et al. (2012); Auyeung et al. (2008)',
    clinicalNote: 'Parent-reported screening instrument for autistic traits in primary-school aged children.',
  },
  mchat: {
    id: 'mchat',
    name: 'Modified Checklist for Autism in Toddlers (M-CHAT-R/F)',
    cutoff: 'Low Risk: 0–2; Medium Risk: 3–7 (triggers follow-up); High Risk: 8–20',
    population: 'Toddlers (16–30 months)',
    source: 'Robins et al. (2014), Pediatrics; AAP Autism Screening Policy',
    clinicalNote: 'Validated early childhood developmental milestone surveillance screener for pediatric well-child checks.',
  },
};

export const GLOSSARY_TERMS = {
  PVT: {
    term: 'Psychomotor Vigilance Task (PVT)',
    abbr: 'PVT',
    definition: 'A validated sustained-attention reaction-time test that measures how rapidly, reliably, and consistently you respond to sudden visual signals.',
  },
  Stroop: {
    term: 'Stroop Color-Word Interference Task',
    abbr: 'Stroop',
    definition: 'A classic executive function test measuring prefrontal response inhibition by asking you to name ink colors while ignoring contradictory printed words.',
  },
  Fixation: {
    term: 'Visual Fixation',
    abbr: 'Fixation',
    definition: 'A brief pause (typically 200–400 milliseconds) where your eyes stay locked on a specific visual target to extract detailed information.',
  },
  Saccade: {
    term: 'Saccadic Eye Movement',
    abbr: 'Saccade',
    definition: 'A rapid, ballistic eye jump moving your focal point between different targets on the screen.',
  },
  IIV: {
    term: 'Intra-Individual Reaction Time Variability',
    abbr: 'IIV',
    definition: 'Trial-to-trial fluctuation in your reaction speed. In cognitive research, elevated variability is a sensitive marker of momentary attentional lapses.',
  },
  SHAP: {
    term: 'SHapley Additive exPlanations (SHAP)',
    abbr: 'SHAP',
    definition: 'An explainable AI technique rooted in cooperative game theory that reveals the exact numerical contribution (+ or -) of each biomarker to your composite score.',
  },
  CPI: {
    term: 'Cognitive Performance Index (CPI)',
    abbr: 'CPI',
    definition: 'A standardized composite benchmark score (calibrated to a general population mean of 75, SD 12) combining executive memory, vigilance, speed, and eye stability.',
  },
};
